name: 2name

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1cut"]
    types:
      - completed

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  process-naming:
    runs-on: ubuntu-latest
    env:
      WORK_DIR_FILE: "${{ secrets.PRIVATE_DIR }}/myPDF工作目录.v"

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Read WORK_DIR from file
        id: read_work_dir
        run: |
          WORK_DIR=$(grep -v -e '^#' -e '^$' "private-repo/$WORK_DIR_FILE" | head -n 1)
          if [ -z "$WORK_DIR" ]; then
            echo "Error: No valid WORK_DIR found in $WORK_DIR_FILE"
            exit 1
          fi
          echo "WORK_DIR=${{ secrets.PRIVATE_DIR }}/$WORK_DIR" >> $GITHUB_ENV
          echo "SOURCE_DIR=${{ secrets.PRIVATE_DIR }}/$WORK_DIR/1cut" >> $GITHUB_ENV
          echo "DEST_DIR=${{ secrets.PRIVATE_DIR }}/$WORK_DIR/2name" >> $GITHUB_ENV

      - name: Initialize workspace
        run: |
          cd private-repo
          rm -rf "${{ env.DEST_DIR }}"
          echo "♻️ 已清空旧2name目录"
          mkdir -p "${{ env.DEST_DIR }}"

      - name: Process files based on TXT content
        run: |
          cd private-repo
          cat << 'EOF' > process_files.py
          import os
          import re

          SOURCE = os.getenv("SOURCE_DIR")
          DEST = os.getenv("DEST_DIR")

          existing_files = [f for f in os.listdir(DEST) if f.endswith('.pdf')]
          counter = max([int(f.split('_')[0]) for f in existing_files]) if existing_files else 0

          all_files = []
          for root, _, files in os.walk(SOURCE):
              for f in files:
                  if f.endswith('.pdf') and any(part in f for part in ['1top', '2mid', '3bot']):
                      all_files.append(os.path.join(root, f))

          def natural_sort_key(s):
              return [int(text) if text.isdigit() else text.lower()
                      for text in re.split(r'(\d+)', s)]

          all_files.sort(key=natural_sort_key)

          for filepath in all_files:
              filename = os.path.basename(filepath)
              match = re.search(r'p(\d+)_(1top|2mid|3bot)', filename)
              if not match:
                  continue

              page_num = match.group(1)
              part_type = match.group(2)
              txt_path = filepath.replace('.pdf', '.txt')

              if os.path.exists(txt_path):
                  with open(txt_path, 'r', encoding='utf-8') as f:
                      content = f.read().strip()
                  if content:
                      counter += 1
                      new_name = f"{counter:04d}_{page_num}{part_type}"
                      os.system(f"cp '{filepath}' '{os.path.join(DEST, new_name)}.pdf'")
                      os.system(f"cp '{txt_path}' '{os.path.join(DEST, new_name)}.txt'")
                      print(f"Processed: {filename} → {new_name}.pdf & .txt")
                  else:
                      os.remove(filepath)
                      os.remove(txt_path)
                      print(f"Deleted empty: {filename} and {os.path.basename(txt_path)}")
              else:
                  print(f"TXT file not found for: {filename}")
          EOF
          python3 process_files.py

      - name: Commit and push results
        run: |
          cd private-repo
          git config user.email "doc-processor@auto"
          git config user.name "Document Processor"

          file_count=$(find "${{ env.DEST_DIR }}" -type f -name "*.pdf" | wc -l)
          commit_msg="Auto: Generated $file_count named slices and paired TXT files"

          git add "${{ env.DEST_DIR }}"
          if git diff --cached --quiet; then
            echo "No staged changes to commit. Skipping commit and push."
            exit 0
          fi
          git commit -m "$commit_msg"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
