name: 3a 换工具

on:
  workflow_dispatch:

jobs:
  process-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils python3-pip
          pip3 install PyMuPDF

      - name: Clean 1cut directory
        run: |
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          if [ -d "$OUTPUT_DIR" ]; then
            rm -rf "$OUTPUT_DIR"/*
          else
            mkdir -p "$OUTPUT_DIR"
          fi

      - name: List PDF files in private repo (root directory only)
        run: |
          find private-repo/${{ secrets.PRIVATE_DIR }} -maxdepth 1 -name "*.pdf" | sort > pdf_files.txt
          echo "Found PDF files:"
          cat pdf_files.txt

      - name: Process PDF files and cut pages into three parts
        run: |
          # 初始化输出目录
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          mkdir -p "$OUTPUT_DIR"

          # 读取文件列表
          mapfile -t pdf_files < pdf_files.txt

          echo "Found ${#pdf_files[@]} PDF files:"
          printf '  - %s\n' "${pdf_files[@]}"

          # 将 Python 逻辑写入临时脚本
          cat << 'EOF' > process_pdf.py
          import fitz  # PyMuPDF
          import os
          import sys

          def process_pdf(pdf_path, output_dir):
              filename = os.path.basename(pdf_path)
              base_name = os.path.splitext(filename)[0]

              # 打开 PDF 文件
              doc = fitz.open(pdf_path)

              # 遍历每一页
              for page_num, page in enumerate(doc):
                  # 获取页面尺寸
                  rect = page.rect
                  width = rect.width
                  height = rect.height

                  # 切割三部分
                  for part_num, (part_name, (y0, y1)) in enumerate([
                      ("1top", (height * 2/3, height)),
                      ("2mid", (height * 1/3, height * 2/3)),
                      ("3bot", (0, height * 1/3))
                  ], 1):
                      # 定义裁剪区域
                      crop_rect = fitz.Rect(0, y0, width, y1)
                      cropped_page = page.get_pixmap(clip=crop_rect)

                      # 保存裁剪后的图像
                      output_path = f"{output_dir}/{base_name}_p{page_num+1}_{part_name}.png"
                      cropped_page.save(output_path)

          if __name__ == "__main__":
              pdf_path = sys.argv[1]
              output_dir = sys.argv[2]
              process_pdf(pdf_path, output_dir)
          EOF

          # 处理每个 PDF 文件
          for pdf_path in "${pdf_files[@]}"; do
              echo "Processing: $pdf_path"
              python3 process_pdf.py "$pdf_path" "$OUTPUT_DIR"
          done

      - name: Commit and push to private repo
        run: |
          cd private-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto: Processed PDF images"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
