name: 3a cut换一个库

on:
  workflow_dispatch:

jobs:
  process-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils python3-pip
          pip3 install pdfCropMargins

      - name: Clean 1cut directory
        run: |
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          if [ -d "$OUTPUT_DIR" ]; then
            rm -rf "$OUTPUT_DIR"/*
          else
            mkdir -p "$OUTPUT_DIR"
          fi

      - name: List PDF files in private repo (root directory only)
        run: |
          find private-repo/${{ secrets.PRIVATE_DIR }} -maxdepth 1 -name "*.pdf" | sort > pdf_files.txt
          echo "Found PDF files:"
          cat pdf_files.txt

      - name: Process PDF files and cut pages into three parts
        run: |
          # 初始化输出目录
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          mkdir -p "$OUTPUT_DIR"

          # 读取文件列表
          mapfile -t pdf_files < pdf_files.txt

          echo "Found ${#pdf_files[@]} PDF files:"
          printf '  - %s\n' "${pdf_files[@]}"

          for pdf_path in "${pdf_files[@]}"; do
              filename=$(basename "$pdf_path")
              echo "Processing: $filename"

              # 切割三部分
              for part_num, (part_name, (y0, y1)) in enumerate([
                  ("1top", (66.66, 100)),
                  ("2mid", (33.33, 66.66)),
                  ("3bot", (0, 33.33))
              ], 1):
                  output_path = f"{OUTPUT_DIR}/{filename}_p{part_name}.pdf"
                  PDF_PATH="$pdf_path" OUTPUT_PATH="$output_path" Y0="$y0" Y1="$y1" python3 <<EOF
              from pdfCropMargins import crop
              import os

              pdf_path = os.getenv("PDF_PATH")
              output_path = os.getenv("OUTPUT_PATH")
              y0 = float(os.getenv("Y0"))
              y1 = float(os.getenv("Y1"))

              # 裁剪PDF
              crop(
                  [pdf_path],
                  outputPath=output_path,
                  percentRetain=(0, y0, 100, y1)  # 定义裁剪区域
              )
              EOF
          done

      - name: Commit and push to private repo
        run: |
          cd private-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto: Processed PDF images"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
