name: 3F PDF Processing

on:
  workflow_dispatch:

jobs:
  process-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils python3-pip cups-pdf cups-client
          sudo usermod -aG lpadmin $USER  # 添加用户到打印组
          pip3 install PyMuPDF
          # 检查 lp 的路径
          which lp || echo "lp not found"
          ls -l /usr/bin/lp || echo "/usr/bin/lp not found"
          ls -l /usr/sbin/lp || echo "/usr/sbin/lp not found"

      - name: Configure CUPS-PDF
        run: |
          OUTPUT_DIR="$GITHUB_WORKSPACE/private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          sudo mkdir -p "$OUTPUT_DIR"
          sudo chmod 777 "$OUTPUT_DIR"
          sudo sed -i "s|^Out .*|Out $OUTPUT_DIR|" /etc/cups/cups-pdf.conf
          sudo sed -i "s|^PassThrough.*|PassThrough jpeg|" /etc/cups/cups-pdf.conf
          sudo sed -i "s|^FilePrefix.*|FilePrefix ''|" /etc/cups/cups-pdf.conf
          sudo systemctl restart cups

      - name: Verify CUPS service
        run: |
          sudo systemctl status cups

      - name: Verify CUPS-PDF printer
        run: |
          lpstat -p PDF

      - name: Create output directory
        run: |
          OUTPUT_DIR="$GITHUB_WORKSPACE/private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          mkdir -p "$OUTPUT_DIR"

      - name: Process PDFs
        run: |
          export PATH="/usr/bin:/usr/sbin:$PATH"
          OUTPUT_DIR="$GITHUB_WORKSPACE/private-repo/${{ secrets.PRIVATE_DIR }}/1cut"

          # 创建临时 Python 脚本
          cat << 'EOF' > process_pdf.py
          import fitz, os, subprocess, time, glob, sys

          def split_pdf(pdf_path, output_dir):
              doc = fitz.open(pdf_path)
              base = os.path.splitext(os.path.basename(pdf_path))[0]
              for pg in range(len(doc)):
                  page = doc[pg]
                  media_box = page.mediabox  # 获取 MediaBox 尺寸
                  width, height = media_box.width, media_box.height

                  for part in ["1top", "2mid", "3bot"]:
                      # 创建分块PDF
                      new_doc = fitz.open()
                      new_doc.insert_pdf(doc, from_page=pg, to_page=pg)
                      new_page = new_doc[0]

                      # 根据 MediaBox 设置 CropBox
                      if part == "1top":
                          crop_box = fitz.Rect(0, 0, width, height / 3)
                      elif part == "2mid":
                          crop_box = fitz.Rect(0, height / 3, width, 2 * height / 3)
                      elif part == "3bot":
                          crop_box = fitz.Rect(0, 2 * height / 3, width, height)
                      new_page.set_cropbox(crop_box)

                      # 保存裁切后的 PDF 到临时文件
                      temp_pdf = f"{base}_p{pg+1}_{part}.pdf"
                      new_doc.save(temp_pdf, deflate=True)
                      new_doc.close()

                      # 提取文本
                      text = new_page.get_textbox(crop_box)
                      txt_path = f"{output_dir}/{base}_p{pg+1}_{part}.txt"
                      with open(txt_path, "w", encoding="utf-8") as f:
                          f.write(text)

                      # 打印 PDF
                      subprocess.run(["lp", "-d", "PDF", temp_pdf])

                      # 等待文件生成
                      for _ in range(5):
                          if glob.glob(f"{output_dir}/{temp_pdf}"):
                              break
                          time.sleep(2)

                      # 清理临时文件
                      os.remove(temp_pdf)

          if __name__ == "__main__":
              if len(sys.argv) != 3:
                  print("Usage: python process_pdf.py <input_pdf> <output_dir>")
                  sys.exit(1)
              split_pdf(sys.argv[1], sys.argv[2])
          EOF

          # 处理所有 PDF 文件
          find "private-repo/${{ secrets.PRIVATE_DIR }}" -name "*.pdf" -print0 | while IFS= read -r -d $'\0' file; do
              echo "Processing: $file"
              python3 process_pdf.py "$file" "$OUTPUT_DIR"
          done

      - name: Commit changes
        run: |
          cd private-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-processed PDFs" 
          git push "https://${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git"
