name: 3F PDF Processing

on:
  workflow_dispatch:

jobs:
  process-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils python3-pip cups-pdf cups-client
          sudo usermod -aG lpadmin $USER  # 添加用户到打印组
          pip3 install PyMuPDF
          # 检查 lpr 的路径
          which lpr || echo "lpr not found"
          ls -l /usr/bin/lpr || echo "/usr/bin/lpr not found"
          ls -l /usr/sbin/lpr || echo "/usr/sbin/lpr not found"

      - name: Configure CUPS-PDF
        run: |
          OUTPUT_DIR="$GITHUB_WORKSPACE/private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          sudo mkdir -p "$OUTPUT_DIR"
          sudo chmod 777 "$OUTPUT_DIR"
          sudo sed -i "s|^Out .*|Out $OUTPUT_DIR|" /etc/cups/cups-pdf.conf
          sudo sed -i "s|^PassThrough.*|PassThrough jpeg|" /etc/cups/cups-pdf.conf
          sudo sed -i "s|^FilePrefix.*|FilePrefix ''|" /etc/cups/cups-pdf.conf
          sudo systemctl restart cups

      - name: Verify CUPS service
        run: |
          sudo systemctl status cups

      - name: Verify CUPS-PDF printer
        run: |
          lpstat -p PDF

      - name: Process PDFs
        run: |
          export PATH="/usr/bin:/usr/sbin:$PATH"
          OUTPUT_DIR="$GITHUB_WORKSPACE/private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          find "private-repo/${{ secrets.PRIVATE_DIR }}" -name "*.pdf" -print0 | while IFS= read -r -d $'\0' file; do
            python3 <<EOF
          import fitz, os, subprocess, time, glob
          def split_pdf(path):
              doc = fitz.open(path)
              base = os.path.splitext(os.path.basename(path))[0]
              for pg in range(len(doc)):
                  for part in ["1top", "2mid", "3bot"]:
                      # 创建分块PDF
                      new_doc = fitz.open()
                      new_doc.insert_pdf(doc, from_page=pg, to_page=pg)
                      new_doc[0].set_cropbox(fitz.Rect(0, 0, 500, 300))  # 示例尺寸
                      temp_pdf = f"{base}_p{pg+1}_{part}.pdf"
                      new_doc.save(temp_pdf)
                      # 打印并等待
                      subprocess.run(["/usr/sbin/lpr", "-P", "PDF", temp_pdf])
                      # 验证生成结果
                      for _ in range(5):
                          if glob.glob(f"{OUTPUT_DIR}/{temp_pdf}"):
                              break
                          time.sleep(2)
                      # 提取文本
                      text = new_doc[0].get_text()
                      with open(f"{OUTPUT_DIR}/{base}_p{pg+1}_{part}.txt", "w") as f:
                          f.write(text)
                      os.remove(temp_pdf)
          split_pdf("$file")
          EOF
          done

      - name: Commit changes
        run: |
          cd private-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-processed PDFs" 
          git push "https://${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git"
