name: 3g 清理pdf

on:
  workflow_dispatch:

jobs:
  process-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils python3-pip
          pip3 install PyMuPDF pillow

      - name: Clean 1cut directory
        run: |
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          if [ -d "$OUTPUT_DIR" ]; then
            rm -rf "$OUTPUT_DIR"/*
          else
            mkdir -p "$OUTPUT_DIR"
          fi

      - name: List PDF files in private repo (root directory only)
        run: |
          find private-repo/${{ secrets.PRIVATE_DIR }} -maxdepth 1 -name "*.pdf" | sort > pdf_files.txt
          echo "Found PDF files:"
          cat pdf_files.txt

      - name: Process PDF files and cut pages into three parts
        run: |
          # 初始化输出目录
          OUTPUT_DIR="private-repo/${{ secrets.PRIVATE_DIR }}/1cut"
          mkdir -p "$OUTPUT_DIR"

          # 将 Python 逻辑写入临时脚本
          cat << 'EOF' > process_pdf.py
          import fitz  # PyMuPDF
          import os
          import sys
          
          def process_pdf(pdf_path, output_dir):
              doc = fitz.open(pdf_path)
              base_name = os.path.splitext(os.path.basename(pdf_path))[0]
          
              for page_num, page in enumerate(doc, 1):
                  media_box = page.rect
                  w, h = int(media_box.width), int(media_box.height)  # 强制转换为整数
          
                  for part_num, (part_name, (y0, y1)) in enumerate([
                      ("1top", (0, h // 3)),
                      ("2mid", (h // 3, 2 * h // 3)),
                      ("3bot", (2 * h // 3, h))
                  ], 1):
                      # 强制转换为整数
                      y0 = int(y0)
                      y1 = int(y1)
                      crop_rect = fitz.Rect(0, y0, w, y1)
          
                      # 验证并限制裁切区域
                      if not media_box.contains(crop_rect):
                          crop_rect = media_box.intersect(crop_rect)
                          if crop_rect.is_empty:
                              print(f"Skipping {part_name} (empty crop area)")
                              continue
          
                      new_doc = fitz.open()
                      new_page = new_doc.new_page(width=crop_rect.width, height=crop_rect.height)
                      new_page.show_pdf_page(
                          fitz.Rect(0, 0, crop_rect.width, crop_rect.height),
                          doc,
                          page_num - 1,
                          clip=crop_rect
                      )
          
                      # 设置 CropBox 前再次验证
                      try:
                          new_page.set_cropbox(crop_rect)
                      except ValueError as e:
                          print(f"Error setting CropBox: {e}. Skipping...")
                          new_doc.close()
                          continue
          
                      new_page.clean_contents()
                      output_pdf_path = f"{output_dir}/{base_name}_p{page_num}_{part_name}.pdf"
                      new_doc.save(output_pdf_path, garbage=4, deflate=True)
                      new_doc.close()
          
                      # 提取文本
                      text = page.get_textbox(crop_rect)
                      txt_path = f"{output_dir}/{base_name}_p{page_num}_{part_name}.txt"
                      with open(txt_path, "w", encoding="utf-8") as f:
                          f.write(text)
          
          if __name__ == "__main__":
              pdf_path = sys.argv[1]
              output_dir = sys.argv[2]
              process_pdf(pdf_path, output_dir)
          EOF

          # 处理每个 PDF 文件
          while IFS= read -r pdf_path; do
              echo "Processing: $pdf_path"
              python3 process_pdf.py "$pdf_path" "$OUTPUT_DIR"
          done < pdf_files.txt

      - name: Commit and push to private repo
        run: |
          cd private-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto: Processed PDF images and extracted text"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
