name: 4merge

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["3find"]
    types:
      - completed

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pdf-merger:
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: ${{ secrets.PRIVATE_DIR }}/3查找
      OUTPUT_DIR: ${{ secrets.PRIVATE_DIR }}/4拼接PDF

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript

      - name: Prepare workspace
        run: |
          cd private-repo
          mkdir -p "$OUTPUT_DIR"
          echo "开始拼接PDF" > merge.log

      - name: Merge and compress PDFs with Ghostscript
        run: |
          cd private-repo

          # 获取所有PDF文件并按自然顺序排序
          pdf_files=($(find "$SOURCE_DIR" -type f -name "*.pdf" | sort -V))

          # 使用Ghostscript合并并压缩PDF
          gs -sDEVICE=pdfwrite \
             -dCompatibilityLevel=1.4 \
             -dPDFSETTINGS=/printer \
             -dNOPAUSE \
             -dQUIET \
             -dBATCH \
             -sOutputFile="${OUTPUT_DIR}/merged_compressed.pdf" \
             "${pdf_files[@]}"

          echo "成功生成合并并压缩后的PDF：${OUTPUT_DIR}/merged_compressed.pdf"

      - name: Merge TXT files with strict check
        run: |
          cd private-repo
          python3 <<EOF
          import os

          source_dir = os.getenv("SOURCE_DIR")
          output_dir = os.getenv("OUTPUT_DIR")
          output_txt_path = os.path.join(output_dir, "merged.txt")

          # 获取所有PDF和TXT文件
          pdf_files = []
          txt_files = []
          for root, _, files in os.walk(source_dir):
              for f in files:
                  if f.lower().endswith('.pdf'):
                      pdf_files.append(os.path.join(root, f))
                  elif f.lower().endswith('.txt'):
                      txt_files.append(os.path.join(root, f))

          # 按文件名排序
          pdf_files.sort()
          txt_files.sort()

          # 检查PDF和TXT文件是否一一对应
          missing_txt_files = []
          for pdf_file in pdf_files:
              txt_file = os.path.splitext(pdf_file)[0] + '.txt'
              if not os.path.exists(txt_file):
                  missing_txt_files.append(os.path.basename(pdf_file))

          if missing_txt_files:
              print("::error::以下PDF文件缺少对应的TXT文件：")
              for file in missing_txt_files:
                  print(f"- {file}")
              exit(1)

          # 检查TXT文件是否有多余的（没有对应的PDF文件）
          extra_txt_files = []
          for txt_file in txt_files:
              pdf_file = os.path.splitext(txt_file)[0] + '.pdf'
              if not os.path.exists(pdf_file):
                  extra_txt_files.append(os.path.basename(txt_file))

          if extra_txt_files:
              print("::error::以下TXT文件缺少对应的PDF文件：")
              for file in extra_txt_files:
                  print(f"- {file}")
              exit(1)

          # 合并TXT文件内容
          with open(output_txt_path, 'w', encoding='utf-8') as outfile:
              for txt_file in txt_files:
                  with open(txt_file, 'r', encoding='utf-8') as infile:
                      outfile.write(infile.read())
                      outfile.write("\n\n")  # 每个TXT文件后插入两个空行

          print(f"成功合并 {len(txt_files)} 个TXT文件到：{output_txt_path}")
          EOF

      - name: Commit results
        run: |
          cd private-repo
          git config user.email "pdf-merger@auto"
          git config user.name "PDF Merger"

          # 生成版本号
          timestamp=$(date +%Y%m%d%H%M%S)
          commit_msg="Auto: 生成优化拼接PDF和汇总TXT（v$timestamp）"

          # 添加更改到暂存区
          git add "$OUTPUT_DIR"

          # 检查是否有 staged 的更改
          if git diff --cached --quiet; then
            echo "No staged changes to commit. Skipping commit and push."
            exit 0
          fi

          # 如果有 staged 的更改，则提交并推送
          git commit -m "$commit_msg"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
