name: 6 E 拼接txt PNG PDF

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["5 E Find and Copy PNG txt"]
    types:
      - completed

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pdf-merger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: ${{ secrets.PRIVATE_DIR }}/3查找
      OUTPUT_DIR: ${{ secrets.PRIVATE_DIR }}/4拼接PDF

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          token: ${{ secrets.PAT }}
          path: private-repo
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev
          pip install Pillow reportlab

      - name: Prepare workspace
        run: |
          cd private-repo
          mkdir -p "$OUTPUT_DIR"
          echo "开始拼接PDF" > merge.log

      - name: Merge images to A4 PDF
        run: |
          cd private-repo
          python3 <<EOF
          import os
          import math
          from PIL import Image
          from reportlab.pdfgen import canvas
          from reportlab.lib.pagesizes import A4
          from reportlab.lib.utils import ImageReader
          import re

          # 配置参数
          A4_WIDTH, A4_HEIGHT = A4
          MM_TO_POINT = 2.83465
          PAGE_WIDTH = A4_WIDTH * MM_TO_POINT
          PAGE_HEIGHT = A4_HEIGHT * MM_TO_POINT
          SECTION_HEIGHT = PAGE_HEIGHT / 3
          MARGIN = 10

          # 获取排序后的文件列表
          def natural_sort_key(s):
              return [int(text) if text.isdigit() else text.lower()
                      for text in re.split(r'(\d+)', os.path.basename(s))]

          all_files = []
          for root, _, files in os.walk(os.getenv("SOURCE_DIR")):
              for f in files:
                  if f.lower().endswith('.png'):
                      all_files.append(os.path.join(root, f))
          all_files.sort(key=natural_sort_key)

          # 创建PDF
          output_path = os.path.join(os.getenv("OUTPUT_DIR"), "merged.pdf")
          c = canvas.Canvas(output_path, pagesize=(PAGE_WIDTH, PAGE_HEIGHT))

          # 分页逻辑
          for i in range(0, len(all_files)):
              # 每3个图片开始新页（除第一页外）
              if i % 3 == 0 and i != 0:
                  c.showPage()
              
              # 获取当前section索引（0-2）
              section = i % 3
              img_path = all_files[i]
              
              try:
                  img = Image.open(img_path)
                  img_reader = ImageReader(img)
                  
                  # 计算缩放
                  img_width, img_height = img.size
                  target_width = PAGE_WIDTH - 2*MARGIN
                  target_height = SECTION_HEIGHT - 2*MARGIN
                  scale = min(target_width/img_width, target_height/img_height)
                  new_width = img_width * scale
                  new_height = img_height * scale
                  
                  # 计算位置
                  x = (PAGE_WIDTH - new_width)/2
                  y = PAGE_HEIGHT - (section+1)*SECTION_HEIGHT + (SECTION_HEIGHT - new_height)/2
                  
                  c.drawImage(img_reader, x, y, new_width, new_height)
              except Exception as e:
                  print(f"处理失败：{img_path} - {str(e)}")
              
              # 补充当前页的空白区域
              if (i == len(all_files)-1) and (section < 2):
                  for s in range(section+1, 3):
                      c.setStrokeColorRGB(0.8, 0.8, 0.8)
                      c.setLineWidth(0.5)
                      y_pos = PAGE_HEIGHT - (s+1)*SECTION_HEIGHT
                      c.rect(MARGIN, y_pos + MARGIN, 
                            PAGE_WIDTH - 2*MARGIN, SECTION_HEIGHT - 2*MARGIN)

          # 保存PDF
          c.save()
          EOF

      - name: Merge TXT files with strict check
        run: |
          cd private-repo
          python3 <<EOF
          import os

          source_dir = os.getenv("SOURCE_DIR")
          output_dir = os.getenv("OUTPUT_DIR")
          output_txt_path = os.path.join(output_dir, "merged.txt")

          # 获取所有png和txt文件
          png_files = []
          txt_files = []
          for root, _, files in os.walk(source_dir):
              for f in files:
                  if f.lower().endswith('.png'):
                      png_files.append(os.path.join(root, f))
                  elif f.lower().endswith('.txt'):
                      txt_files.append(os.path.join(root, f))

          # 按文件名排序
          png_files.sort()
          txt_files.sort()

          # 检查png和txt文件是否一一对应
          missing_txt_files = []
          for png_file in png_files:
              txt_file = os.path.splitext(png_file)[0] + '.txt'
              if not os.path.exists(txt_file):
                  missing_txt_files.append(os.path.basename(png_file))

          if missing_txt_files:
              print("::error::以下png文件缺少对应的txt文件：")
              for file in missing_txt_files:
                  print(f"- {file}")
              exit(1)

          # 检查txt文件是否有多余的（没有对应的png文件）
          extra_txt_files = []
          for txt_file in txt_files:
              png_file = os.path.splitext(txt_file)[0] + '.png'
              if not os.path.exists(png_file):
                  extra_txt_files.append(os.path.basename(txt_file))

          if extra_txt_files:
              print("::error::以下txt文件缺少对应的png文件：")
              for file in extra_txt_files:
                  print(f"- {file}")
              exit(1)

          # 合并txt文件内容
          with open(output_txt_path, 'w', encoding='utf-8') as outfile:
              for txt_file in txt_files:
                  with open(txt_file, 'r', encoding='utf-8') as infile:
                      outfile.write(infile.read())
                      outfile.write("\n\n")  # 每个txt文件后插入两个空行

          print(f"成功合并 {len(txt_files)} 个txt文件到：{output_txt_path}")
          EOF

      - name: Commit results
        run: |
          cd private-repo
          git config user.email "pdf-merger@auto"
          git config user.name "PDF Merger"

          # 生成版本号
          timestamp=$(date +%Y%m%d%H%M%S)
          commit_msg="Auto: 生成拼接PDF和汇总TXT（v$timestamp）"

          git add "$OUTPUT_DIR"
          git commit -m "$commit_msg"
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ secrets.PRIVATE_REPO }}.git" main
